### ISSUE TITLE
'Decodable' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by bcbear-gun** [livio/HelloTrello#2]
I can't compile HelloTrello in Xcode 9.2.

The error : 'Decodable' is ambiguous for type lookup in this context

**Comment by joeljfischer** [comment]
Fixed in 0.3.0

**Comment by bcbear-gun** [comment]
Just updated?
Thanks. I will try.

**Comment by bcbear-gun** [comment]
Can I create trello card and add attachment using this app?

**Comment by joeljfischer** [comment]
Nope, but you should be able to add that functionality and create a pull request if you want it.

**Comment by bcbear-gun** [comment]
Thanks.
I copy and paste your code and make new project.
and add create card feature.
I fix Decodable issue by copying Decodable class files and change class name.

https://github.com/Hades0103/MyTrelloApp
My project.
